spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.bailiban.springboot.model
  mapper-locations: mapper/*.xml
